import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Procurement of Computer Equipment for IT Company',
    rating: 5,
    ratingCount: 10,
    // price: 300,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/workshop.jpg',
    title: 'Workshop Consumables',
    rating: 5,
    ratingCount: 15,
    // price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/roads1.jpg',
    title: 'Asphalting of Local and Unclassified Roads',
    rating: 4,
    ratingCount: 7,
    // price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/schools.jpg',
    title: 'School for of Children, Kindergarten',
    rating: 4,
    ratingCount: 12,
    // price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/office.jpg',
    title: 'Office Furniture',
    rating: 4,
    ratingCount: 32,
    // price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/lab.jpg',
    title: 'Consumable Laboratory Supplies',
    rating: 5,
    ratingCount: 14,
    // price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/mobilee.jpg',
    title: 'Procurement of Fixed, Mobile Telecommunication',
    rating: 4,
    ratingCount: 6,
    // price: 25,
    category: 'Beginner',
  },
]
